### ISSUE TITLE
Compile natively on ARM?

### ISSUE THREAD

**Issue by jedichen121** [google-coral/libcoral#11]
I'm wondering if this repo can support native compile on ARM system, such as Raspberry Pi? I want to use libcoral with some middleware which I'm not sure if it can be cross-compiled or not. Thank you.

**Comment by manoj7410** [comment]
@jedichen121 Doesn't it help https://github.com/google-coral/libcoral#linux ?

**Comment by manoj7410** [comment]
Feel free to reopen if you still face any issue with the compilation.
