### ISSUE TITLE
make tests error glib.h not found on Ubuntu 20.04 (Windows 10 WSL)

### ISSUE THREAD

**Issue by 0ric1** [google-coral/libcoral#12]
coral/dmabuf/model_pipelining_dmabuf_devboard_test.cc:7:10: fatal error: glib.h: No such file or directory

glib.h found in:
ibglib2.0-dev: /usr/include/glib-2.0/glib.h
libhiredis-dev: /usr/include/hiredis/adapters/glib.h
syslog-ng-dev: /usr/include/syslog-ng/compat/glib.h

make benchmarks, make examples and make tools build successfully.

**Comment by manoj7410** [comment]
@0ric1 Are you building the library with Docker ?

**Comment by 0ric1** [comment]
No, I used Ubuntu in Windows-Subsystem für Linux and called `make tests`

**Comment by hjonnala** [comment]
@0ric1, Can you try running the commands using docker command below?

make DOCKER_IMAGE=ubuntu:18.04 DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build

Docker is recommended as it allows to avoid complicated environment setup and build binaries for Linux on other operating systems without complicated setup. 

Please note that, the above command took almost 3 hours to execute the command fully on my windows machine.

Docker installation link: https://docs.docker.com/engine/install/ubuntu/
Start docker daemon using:  sudo dockerd
Resolve docker permission error using : sudo chmod 666 /var/run/docker.sock

**Comment by 0ric1** [comment]
Sorry I can't test this, because don't want to install docker, if docker is mandatory, you can close this issue and I can't use this library.

**Comment by manoj7410** [comment]
@0ric1 It is not mandatory to work with Docker but it makes the life easy by reducing the dependency problem. If you want to try without Docker then most probably every dependency problem needs to be resolved manually. 

The DockerFile given at https://github.com/google-coral/libcoral/blob/master/docker/Dockerfile explains about the required  dependencies for this build. 
You can try to install these dependencies manually and then try to build.

**Comment by hjonnala** [comment]
unfortunately, as of now we don't have any official support for WSL installations of libcoral without Docker image. Sorry for inconvenience.

**Comment by multi-stream** [comment]
Built this natively and with docker, both failed the same way:
coral/dmabuf/model_pipelining_dmabuf_devboard_test.cc:22:10: fatal error: glib.h: No such file or directory
 #include <glib.h>
          ^~~~~~~~
