### ISSUE TITLE
WORKSPACE new_local_repository system_linux path is wrong on Ubuntu 20.04 (Windows 10 WSL)

### ISSUE THREAD

**Issue by 0ric1** [google-coral/libcoral#13]
must be `path = "/usr/lib",`
instead of `path = "/usr/system_libs",`

**Comment by hjonnala** [comment]
@0ric1 can you please share the error you are getting because of path = "/usr/system_libs"

**Comment by 0ric1** [comment]
I called: `make tests` the result was:
`
ERROR: /mnt/c/Users/user/libcoral/WORKSPACE:86:21: fetching new_local_repository rule //external:system_linux: java.io.IOException: The repository's path is "/usr/system_libs" (absolute: "/usr/system_libs") but this directory does not exist.
ERROR: /mnt/c/Users/user/libcoral/coral/dmabuf/BUILD:7:8: //coral/dmabuf:dmabuf_devboard_test depends on @system_linux//:gstallocators in repository @system_linux which failed to fetch. no such package '@system_linux//': The repository's path is "/usr/system_libs" (absolute: "/usr/system_libs") but this directory does not exist.
ERROR: /mnt/c/Users/user/libcoral/coral/dmabuf/BUILD:7:8: //coral/dmabuf:dmabuf_devboard_test depends on @system_linux//:gstreamer in repository @system_linux which failed to fetch. no such package '@system_linux//': The repository's path is "/usr/system_libs" (absolute: "/usr/system_libs") but this directory does not exist.
ERROR: Analysis of target '//coral/dmabuf:dmabuf_devboard_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 33.069s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (28 packages loaded, 110 targets configured)
`

**Comment by hjonnala** [comment]
I have tried making that change execute **make tests** command. It is not successful. Please let us know if you are able to run the command **make tests** without fail.

**Comment by 0ric1** [comment]
It still fails, because of the other issue https://github.com/google-coral/libcoral/issues/12 so I think you need to fix both issues to be able to compile.

**Comment by hjonnala** [comment]
unfortunately, as of now we don't have any official support for WSL installations of libcoral without Docker image. Sorry for inconvenience.
