### ISSUE TITLE
Transfer Learning for Object Detection

### ISSUE THREAD

**Issue by abucka** [google-coral/libcoral#17]
### Description

Hi,

I would like to ask if there is also a possibility to use transfer learning to retrain an object detection model like it is implemented for image classification? 

I would appreciate if you could give me some hints.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Coral Device

USB Accelerator

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @abucka  Unfortunately on device transfer Learning for Object Detection  is not supported.

Please check the Colab   transfer learning tutorials. Thanks!
https://github.com/google-coral/tutorials#colab-tutorials-for-coral
