### ISSUE TITLE
Where is the linked library?

### ISSUE THREAD

**Issue by tyouritsugun** [google-coral/libcoral#19]
Hi

I want to use the static or dynamic library of libcoral. However, I can not find any *.a or *.so in the `out` directory after I built this project within the docker build. Can anyone help me find the output  *.a or *.so?

Zhang

**Comment by hjonnala** [comment]
Hello @tyouritsugun libcoral is pure C++ code. It won't generate any *.a or *.so files. To use libcoral, you must compile the library with your project using [Bazel](https://bazel.build/) (we do not offer a shared library).  Please check the below link to run inference with the Libcoral API. 

https://coral.ai/docs/edgetpu/tflite-cpp/#run-an-inference-with-the-libcoral-api

**Comment by tyouritsugun** [comment]
@hjonnala 

Thank you for your reply.
My current working project is not compatible with Bazel and Docker build and changing them is an almost impossible work. Please kindly consider to output *.a, *.so, and header files in your next version.
Since I only need the pipeline function of libcoral, I think I need to write a build script to integrate the source to my project. I might meet some conflicts, but for now it's the lesser of two evils, I think.

Thank you in advance
tyouritisugun

**Comment by hjonnala** [comment]
@tyouritsugun  sure, will pass the info to the internal team for consideration. Thanks!

**Comment by mattymactutor** [comment]
I have the same issue. I have a multi-library, multi-source project of over 2 years. Now I'm trying to add in coral support. I've never used Bazel before. You're saying that I have to learn how to adapt the Bazel build file from the examples and make them work with my source code files and current libraries?  I've been at this for 2 weeks. The bazel build and the Docker build both throw errors on my RPI 4, but I've gotten the library to build on my Linux system. I was hoping to build there for arm and copy paste the .a or .so so I don't have to change my entire build. ( I submitted help tickets for the google coral but it forwards to ASUS and they dont answer)

**Comment by hjonnala** [comment]
Hello @mattymactutor here is an example on how to write custom scripts and build with libcoral: https://github.com/google-coral/edgetpu/issues/600#issuecomment-1145076778

And it seems one user is able to generate a shared object library file for libcoral, but I am not sure how he was able to do it though: https://github.com/google-coral/libcoral/issues/16#issuecomment-1020383165

**Comment by phil-fill** [comment]
I am new to libcoral and cpp programming. I want to run a model on the edgetpu. I followed the tutorial to compile libcoral with bazel and docker on my pi https://github.com/google-coral/libcoral. What is the result of the compilation(which file). What do i have to include into my .cpp file to use the coral::func stuff? In their examples https://coral.ai/docs/edgetpu/tflite-cpp/#inferencing-example i cant see nothing that they import.  

Best wishes Jean
