### ISSUE TITLE
how to install the compile lib

### ISSUE THREAD

**Issue by timocafe** [google-coral/libcoral#21]
### Description

Hello, 

I succeed to make inference using python on the coral TPU on my own model. However I would like use the C++ API for performance issue. The coral website give example and some [indication](https://coral.ai/docs/edgetpu/tflite-cpp/#run-an-inference-with-the-libcoral-api) , I compile the library on my mac and then ? There is no target `make install` or any indication of which files I should copy between my mac and the TPU. I need tflite (include and lib), the runtime edgtpu and maybe something else.

So does somebody could indicate me which files I should copy to the TPU ? A update of the README will be very nice too.

Thank you

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mac OS

### Coral Device

Dev Board Mini

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by Namburger** [comment]
@timocafe with bazel you can point to libedgetpu as a dependency in a `WORKSPACE` file, take a look at how it is done in this example: 
https://github.com/google-coral/examples-camera/tree/master/nativeapp

Cheers!

**Comment by timocafe** [comment]
oki so cross compilation and scp ...

**Comment by timocafe** [comment]
OK I have been able to compile the app, indeed it is a tpu binary (check with ldd), I have no Usb cam so I can not really test it. However a few questions, I do not see any trace of the edgelib, tflite, does bazel did a static lib and included into the binary ? 

Does it exist a way to speed up the compilation, the first run was slow due to setup. However if I recompile, bazel "re-fetch" everything and it look likes it recompiles flat buffer, tflite ... So a single compile takes 100 [s] ... :-/ 
Cheers

**Comment by timocafe** [comment]
find I can start a shell inside the docker, just have to compile tflite once.

**Comment by timocafe** [comment]
Ok the strategy is to make a binary on my mac and copy it on the TPU. Bazel
will do the cross compiling. Let's see ..
