### ISSUE TITLE
Building and Running libcoral examples

### ISSUE THREAD

**Issue by adam100150** [google-coral/libcoral#28]
### Description

I was successfully able to build the libcoral examples but when I try running them I get an error that one of the model files is missing. How should I go about solving this?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Mac OS

### Programming Language

C++

### Relevant Log Output

```shell
ERROR: Could not open 'mobilenet_v1_1.0_224_quant_edgetpu.tflite'. 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F20221027 09:20:25.676702 161830400 tflite_utils.h:242] Check failed: 'tflite::FlatBufferModel::BuildFromFile(path.c_str())' Must be non NULL 
*** Check failure stack trace: ***
[1]    13657 abort      ./classify_image
```
</details>

**Comment by hjonnala** [comment]
Hello @adam100150 please try the passing the model, image and labels as arguments. You can get the sample data from test_data repo: https://github.com/google-coral/test_data.. Thanks!!

```
hemanth:~/libcoral/out/k8/examples$ ./classify_image --model_path /home/pycoral/test_data/mobilenet_v1_1.0_224_quant_edgetpu.tflite --image_path "/home/pycoral/test_data/bird.rgb" --labels_path "/home/pycoral/test_data/imagenet_labels.txt"
Input data does not require preprocessing.
---------------------------
chickadee
Score: 0.820312
---------------------------
magpie
Score: 0.078125
---------------------------
water ouzel, dipper
Score: 0.0429688

```
