### ISSUE TITLE
examples build error

### ISSUE THREAD

**Issue by jthoms** [google-coral/libcoral#3]
Hi, I'm trying to build the examples from libcoral directory, on Ubuntu 20.04, Docker version 19.03.12, build 48a66213fe:
`sudo make DOCKER_IMAGE=debian:stretch DOCKER_CPUS="aarch64" DOCKER_TARGETS="examples" docker-build`
Fails on final step: ERROR: no such package '@libedgetpu//
Please see step 13 output below:

Step 13/13 : RUN wget -O /bazel https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh &&     bash /bazel &&     rm -f /bazel
 ---> Using cache
 ---> 42243aca8920
Successfully built 42243aca8920
Successfully tagged coral-edgetpu-debian-stretch:latest
docker run --rm -i --tty -v /home/jthoms/coral/libcoral/:/workspace \
    "coral-edgetpu-debian-stretch" /bin/bash -c "chmod a+w /; groupadd --gid 0 root; useradd -m -e '' -s /bin/bash --gid 0 --uid 0 root; echo 'root ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers; su root -c 'for cpu in aarch64; do make CPU=\${cpu} COMPILATION_MODE=opt -C /workspace/ examples || exit 1; done'"
groupadd: group 'root' already exists
useradd: user 'root' already exists
make: Entering directory '/workspace'
bazel build --compilation_mode=opt --copt=-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION --verbose_failures --sandbox_debug --subcommands --define PY3_VER=35 --action_env PYTHON_BIN_PATH=/usr/bin/python3 --cpu=aarch64 --define darwinn_portable=1 --experimental_repo_remote_exec --crosstool_top=@crosstool//:toolchains --compiler=gcc --linkopt=-l:libusb-1.0.so --linkopt=-Wl,--strip-all --copt=-ffp-contract=off //coral/examples:two_models_one_tpu \
                                 //coral/examples:two_models_two_tpus_threaded \
                                 //coral/examples:model_pipelining \
                                 //coral/examples:classify_image \
                                 //coral/examples:backprop_last_layer
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: no such package '@libedgetpu//': In new_local_repository rule //external:libedgetpu the 'build_file' attribute does not specify an existing file (/workspace/libedgetpu/BUILD does not exist)
INFO: Elapsed time: 4.080s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
Makefile:121: recipe for target 'examples' failed
make: *** [examples] Error 1
make: Leaving directory '/workspace'
make: *** [/home/jthoms/coral/libcoral/docker/docker.mk:40: docker-build] Error 1

**Comment by dmitriykovalev** [comment]
You need to clone [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules): 

```bash
git submodule init
git submodule update
```
There are two of them: `libedgetpu` and `test_data`.

**Comment by jthoms** [comment]
Worked, thanks!
