### ISSUE TITLE
How to use build artifacts from docker build

### ISSUE THREAD

**Issue by alexanderfrey** [google-coral/libcoral#6]
Hi,

I'm building libcoral for the xavier nx platform. Since I had no luck in building it directly on the xavier I choosed to do cross compilation on my host computer with the docker build:

`make DOCKER_IMAGE=ubuntu:18.04 DOCKER_CPUS="k8 armv7a aarch64" DOCKER_TARGETS=tests docker-build`

After the build finishes I would like to transfer the library libcoral to the xavier from the docker image. How do I do that  and where is the library exactly ?

Thanks
Alexander

**Comment by Namburger** [comment]
@alexanderfrey after building the binaries should be i the "out" directory

**Comment by Archie3d** [comment]
I can see only `*_test` binaries in the `out/` folder after the build. Where are the libraries to link against?
