### ISSUE TITLE
Fail to build due to "missing dependency declarations"

### ISSUE THREAD

**Issue by Haag-se** [google-coral/libcoral#9]
I run into errors when trying to cross-compile libcoral with "make CPU=aarch64 all".

Hardware: Raspberry Pi 4
OS: Ubuntu 20.04.2 LTS (focal)
Architecture: 64-bit aarch64
GCC version: 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
Bazel version: 4.0.0

`ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/5ba4c4366753ce2739652ff638356e7a/external/flatbuffers/src/BUILD:40:11: Compiling src/flatc_main.cpp [for host] failed: undeclared inclusion(s) in rule '@flatbuffers//src:flatc':
this rule is missing dependency declarations for the following files included by 'src/flatc_main.cpp':
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stddef.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stdarg.h'
  '/usr/lib/gcc/aarch64-linux-gnu/9/include/stdint.h'`

The header-files mentioned does exist at the given path.

I have tried to clear Bazel with "bazel clean --expunge" and "rm -rf ~/.cache/bazel". I've also tried to add "--action_env CPLUS_INCLUDE_PATH=/usr/lib/gcc/aarch64-linux-gnu/9/include" to BAZEL_BUILD_FLAGS in the makefile.

I'm stuck. Any help would be much appreciated!

**Comment by Namburger** [comment]
@Haag-se Hello, this build isn't meant to be done on arm platform, it supposed to be a cross build from x86-64 and you copy the binaries to your arm machines

**Comment by Haag-se** [comment]
> @Haag-se Hello, this build isn't meant to be done on arm platform, it supposed to be a cross build from x86-64 and you copy the binaries to your arm machines

Makes perfect sense! Thank you for helping me out. I spent way to much time googling on how to fix something that wasn't supposed to be fixed :)
